config/routes.rb
Rails.application.routes.draw do
  root "articles#index"
  resources :articles do
    resources :comments
  end
  resources :searches
  devise_for :users
end

app/models/article.rb
class Article < ActiveRecord::Base
  has_many :comments
  validates :content, :presence => true
  def add_point(count=1)
    update_attribute(:rating, rating + count)
  end
  def subtract_point(count=1)
    update_attribute(:rating, count - rating)
  end
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :article
  validates :user, :presence => true
  validates :content, :presence => true
  has_ancestry
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

  before_action :find_article, except: [:index, :new, :create]

  def index
    if (params[:sort])
      if (params[:sort] == "Alphabetical ASC")
        @articles = Article.all.sort{|a, b| a.title <=> b.title}
      elsif (params[:sort] == "Alphabetical DESC")
        @articles = Article.all.sort{|a, b| b.title <=> a.title}
      elsif (params[:sort] == "Newest")
        @articles = Article.all.sort{|a, b| b.created_at <=> a.created_at}
      else
        @articles = Article.all.sort{|a, b| a.created_at <=> b.created_at}
      end
    else
      @articles = Article.all
    end
  end

  def show
  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(article_params)
    @article.update_attribute(:rating, 0)
    if @article.save
      redirect_to articles_path
    else
      render :new
    end
  end

  def destroy
    @comments = @article.comments
    @comments.each do |comment|
      comment.destroy
    end
    @article.destroy
    redirect_to articles_path
  end

  def edit
    render :edit
  end

  def update
    @article.update(article_params)
    if @article.save
      redirect_to articles_path
    else
      render :edit
    end
  end

  def upvote
    # binding.pry
    @article.add_point
    # @article.add_point
    # redirect_to article_path(@article)
  end

  def downvote
    @article.subtract_point
  end

  private
    def article_params
      params.require(:article).permit(:content, :author, :title, :rating)
    end
    def find_article
      @article = Article.find(params[:id])
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  before_action :find_comment_and_article, except: [:index, :new, :create]

  def index
    @comments = Comment.all
    @article = Article.find(params[:article_id])
  end

  def show
    binding.pry
  end

  def new
    @article = Article.find_by_id(params[:article_id])
    @parent_comment = Article.find_by_id(params[:parent_id])
    if (@article)
      @comment = Comment.new
    else
      @comment = Comment.new(:parent_id => params[:parent_id])
    end
    render :new
  end

  def create
    @article = Article.find_by_id(params[:article_id])
    @parent_comment = Comment.find_by_id(params[:parent_id])
    if (@article)
      new_comment = @article.comments.new(comment_params)
      if (new_comment.save)
        redirect_to article_path(@article)
      else
        render :new
      end
    else
      new_comment = Comment.new(comment_params)
      if (new_comment.save)
        binding.pry
        redirect_to comment_path(@parent_comment)
      else
        render :new
      end
    end

    # if @article.save
    #   redirect_to article_path()
    # @article = Article.find(params[:article_id])
    # @comment = @article.comments.new(comment_params)

    # if @comment.save
    #   redirect_to article_path(@article)
    # else
    #   render :new
    # end
    # if (params[:article_id])
    #   @parent = Article.find(params[:article_id])
    #   @article = @parent
    # else
    #   @parent = Comment.find(params[:comment_id])
    #   @article = Article.find(params[:article])
    # end
    # @comment = @parent.comments.new(comment_params)
    # @comment.save
    # if @article
    #   redirect_to article_path(@article)
    # else
    #   redirect_to articles_path
    # end

  end

  def destroy
    @comment.destroy
    redirect_to article_path(@article)
  end

  def edit
    render :edit
  end

  def update
    @comment.update(comment_params)
    if @comment.save
      redirect_to article_path(@article)
    else
      render :edit
    end
  end


  private
    def comment_params
      params.require(:comment).permit(:content, :user, :parent_id)
    end
    def find_comment_and_article
      @comment = Comment.find(params[:id])
      @article = Article.find(params[:article_id])
    end
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController

  def index
    @search_results = Article.search(params[:q])
    render :index
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/views/articles/_form.html.erb
<%= form_for @article do |f| %>
  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :author %>
    <%= f.text_field :author, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :content %>
    <%= f.text_area :content, cols: 10, rows: 10,  class: 'form-control' %>
  </div>
  <%= f.submit class: 'btn btn-primary' %>
<% end %>

app/views/articles/edit.html.erb
<%= render 'form' %>

app/views/articles/index.html.erb
<div class="container">
  <br>
  <div class="row">
    <div class="col-md-4">
    </div>
    <div class="col-md-4 text-center">
      <div id="create_article_button">
        <%= link_to 'Create a New Article', new_article_path, class: "btn btn-primary" if current_user%>
      </div>
      <br>
    </div>
    <div class="col-md-4">
      <div id="sort_button" class="pull-right">
        <%= form_tag(articles_path, method: 'GET', class:'sort') do %>
        <%= select_tag :sort, options_for_select([["A-Z", "Alphabetical ASC"], ["Z-A", "Alphabetical DESC"], ["Newest", "Newest"], ["Oldest", "Oldest"]]) %>
        <%= submit_tag 'Sort' %>
        <% end %>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-md-2">
      <div id="side_well" class="well">
        Popular Feeds
        <br>
        <br>
        <li><%= link_to 'Microsoft'%></li>
        <li><%= link_to 'Apple'%></li>
        <li><%= link_to 'Oracle'%></li>
        <li><%= link_to 'Facebook'%></li>
        <li><%= link_to 'Google'%></li>
      </div>
    </div>
    <div class="col-md-10 nopadding">

      <ul id="article_list_ul">
        <% @articles.each do |article| %>
        <div class="well">
          <li id="article_list">
            <%= link_to article.title, article_path(article), class: 'title' %><br>
            <p class="metadata">by <%= article.author %> |</p>
            <p class="metadata"><%= article.content %></p>
            <% if current_user %>
            <%= link_to article_path(article), data: {confirm: "Are you sure?", method: "delete"} do %>
            <span class="glyphicon glyphicon-trash"></span> Delete
            <% end %>
            <%= link_to edit_article_path(article) do %>
            <span class="glyphicon glyphicon-edit"></span> Edit
            <% end %>
            <% end %>
          </li>
        </div>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/articles/show.html.erb
<div class="col-sm-12">
  <h1 class="title"><%= @article.title %></h1>
  <p class="author"><%= @article.author %></p>
  <p class="content"><%= @article.content %></p>
  <p class="metadata"><%= @article.created_at.strftime("Created on %m/%d/%Y at %I:%M%p") %></p>


  <div class="comments-header">
    <h4 class="comments-title">Comments</h4>
    <%= link_to 'New Comment', new_article_comment_path(@article), class: "btn btn-primary pull-right new-comment" if current_user %>
  </div>
  <ul class="list-unstyled">
    <% @article.comments.each do |comment| %>
      <li>
        <%= comment.content %><br>
        <%= comment.user %><br>
        <%= comment.created_at.strftime("Created on %m/%d/%Y at %I:%M%p") %>
        <% if current_user %>
          <%= link_to 'Delete', article_comment_path(@article, comment), data: {confirm: "Are you sure?", method: "delete"} %> |
          <%= link_to 'Edit', edit_article_comment_path(@article, comment) %>
        <% end %>
      </li>
    <% end %>
  </ul>



</div>

app/views/comments/_form.html.erb
<%= form_for [@article, @comment] do |f| %>
  <%= f.hidden_field :parent_id %>
  <div class="form-group">
    <%= f.label :user %>
    <%= f.text_field :user, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :content %>
    <%= f.text_area :content, cols: 10, rows: 10,  class: 'form-control' %>
  </div>
  <%= f.submit class: "btn btn-primary" %>
<% end %>

app/views/comments/edit.html.erb
<%= render 'form' %>

<%= link_to 'Back', article_path(@article) %>

app/views/comments/index.html.erb
<div class="container">
  <ul>
    <%= @comments.each do |comment| %>
      <% comment.user %>
      <% comment.content %>
    <% end %>
  </ul>
  <%= link_to 'Create a new Comment', new_article_comment_path(@article) %>
</div>

app/views/comments/new.html.erb
<%= render 'form' %>

app/views/comments/show.html.erb
<p><%= @comment.user %></p>
<p><%= @comment.content %></p>

<% @comment.children.each do |comment| %>
  <li>
    <%= link_to comment.content, article_comment_path(@article, comment) %><br>
    <%= comment.user %>
    <% if current_user %>
      <%= link_to 'Delete', comment_path(@article, comment), data: {confirm: "Are you sure?", method: "delete"} %> |
      <%= link_to 'Edit', edit_comment_path(@article, comment) %>
      <%= link_to 'Reply', new_comment_path(comment) %> <!-- TODO: Figure out Nested Routing -->
    <% end %>
  </li>
<% end %>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">All Things Tech</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">

      </ul>
      <ul class="nav navbar-nav navbar-right">
        <% if current_user %>
          <li><%= link_to 'Sign Out', destroy_user_session_path, method: 'delete' %></li>
        <% else %>
          <li><%= link_to 'Sign In', new_user_session_path %></li>
        <% end %>
        <li><%= link_to 'Search', searches_path %></li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FanSite</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <link href='https://fonts.googleapis.com/css?family=Lato:400,700,900,300' rel='stylesheet' type='text/css'>
  </head>
  <body>
    <%= render 'layouts/navbar' %>
    <div class="container-fluid">
      <div class="row">
        <p class="notice"><%= notice %></p>
        <p class="alert"><%= alert %></p>
        <%= yield %>
      </div>
    </div>
  </body>
</html>

app/views/searches/index.html.erb
<%= form_tag(searches_path, method: 'GET') do %>
  <%= label_tag(:q, "Search for:") %>
  <%= text_field_tag(:q, nil, placeholder: "Search") %>
  <%= submit_tag("Search") %>
<% end %>

<% if @search_results.any? %>
  <% @search_results.each do |result| %>
    <%= link_to result.content, articles_path(result) %>
  <% end %>
<% end %>